name: Create new release

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    #runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Get appimagetool
      run: |
        set -x
        #wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"

        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        pwd; ls -lah

    - name: Make AppImage
      run: |
        set -x
        version="1.9.0"
        echo "Gromit-MPX version: $version"
        tag=1 #1

        wget -q "https://github.com/ryuuzaki42/Gromit-MPX_AppImage/releases/download/${version}_0_txz/gromit-mpx-${version}-x86_64-1_JB.txz"

        mkdir squashfs-root/
        tar -xvf "gromit-mpx-${version}-x86_64-1_JB.txz" -C squashfs-root/
        cd squashfs-root/

        ln -s usr/share/icons/hicolor/scalable/apps/net.christianbeier.Gromit-MPX.svg net.christianbeier.Gromit-MPX.svg
        ln -s usr/share/applications/net.christianbeier.Gromit-MPX.desktop Gromit-MPX.desktop
        cat Gromit-MPX.desktop
        pwd; ls -lah

        echo '#!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"

        echo "XDG_CONFIG_HOME: $XDG_CONFIG_HOME"
        if [ "$XDG_CONFIG_HOME" != "" ]; then # If use --appimage-portable-config
            config_path="$XDG_CONFIG_HOME/"
        else
            config_path="$HOME/.config/"
        fi

        if [ ! -f "$config_path/gromit-mpx.cfg" ]; then # Check if configuration file exists
            echo "Configuration not found! - Coping default one"
            cp "$HERE"/etc/gromit-mpx/gromit-mpx.cfg "$config_path"
        fi
        echo "Gromit-MPX configuration file: $config_path/gromit-mpx.cfg"

        "$HERE"/usr/bin/gromit-mpx $@' > AppRun
        chmod +x AppRun
        cat AppRun

        cd ../
        cp README.md squashfs-root/

        ARCH=x86_64 VERSION="${version}-${tag}_JB" ./appimagetool-x86_64.AppImage squashfs-root/
        pwd; ls -lah

        fileName=$(ls Gromit-MPX*.AppImage)
        echo "fileName: $fileName"
        md5sum "$fileName" > "${fileName}.md5"
        pwd; ls -lah

    - uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "Gromit-MPX*.AppImage; Gromit-MPX*.zsync; Gromit-MPX*.md5"
          #overwrite: true
          verbose: true
          draft: false
          default_release_name: "Gromit-MPX V in AppImage"
